-- Master seed registry: verified official sources only.
-- Coverage: verified (opened/confirmed), partial (part of fact only),
-- missing (expected, retry later), not_published (institute doesn't publish).

insert into public.college_facts
  (institute, topic, subtype, claim, source_url, source_title, publisher, published_ay, format, coverage)
values
-- ── IIT Bombay ──
('IIT Bombay','placements','portal','Placement portal with reports 2020-21 to 2023-24. No public branch-wise median table.','https://campus.placements.iitb.ac.in/','Placement Office portal','IIT Bombay Placement Office','','html','partial'),
('IIT Bombay','rules','ug-rulebook','UG rulebook (June 2025): branch change, grading, minor/honors.','https://acad.iitb.ac.in/files/UG_RULE_BOOK.pdf','UG Rule Book','IIT Bombay Academic Office','','pdf','verified'),
('IIT Bombay','fees','circular','Fee circulars hub: academic + hostel + remission OM, SC/ST/PwD tuition waiver pattern.','https://acad.iitb.ac.in/admissions/fees-structure','Fees structure hub','IIT Bombay Academic Office','2026-27','html','verified'),
('IIT Bombay','support','hub','Support hub: SWC counselling, SC/ST, PwD, Gender Cell, hospital in one place.','https://dosa.iitb.ac.in/support-system','Support system','IIT Bombay Dean SA','','html','verified'),
('IIT Bombay','startup','ecell-incubator','E-Cell (est 1998) + SINE incubator (TBI since 2004) + Desai Sethi School.','https://www.iitb.ac.in/industry/entrepreneurship','Entrepreneurship hub','IIT Bombay','','html','verified'),
('IIT Bombay','media','student','Insight: official student media body, verified via gymkhana listing.','https://insightiitb.org/','Insight IIT Bombay','Student media body','','html','verified'),
-- ── IIT Delhi ──
('IIT Delhi','placements','portal','OCS portal + press releases. No standalone BTech report PDF; MBA reports only. Branch-wise BTech not officially released.','http://ocs.iitd.ac.in/','Office of Career Services','IIT Delhi OCS','','html','partial'),
('IIT Delhi','rules','ug-rules','UG Programme Rules + Curriculum 2025 hub (branch change CGPA 8.0/7.0, cap 115%).','https://home.iitd.ac.in/curriculum.php','Curriculum hub','IIT Delhi','','html','verified'),
('IIT Delhi','fees','circular','Fee circulars hub incl UG Entry 2025-26; SC/ST/PwD 100% tuition waiver.','https://academics.iitd.ac.in/circulars','Circulars hub','IIT Delhi Academics','2026-27','html','verified'),
('IIT Delhi','support','diversity','ODI diversity office: IGES gender unit, Indradhanu, OAE, BSW counselling.','https://odi.iitd.ac.in/ourTeam','Diversity and Inclusion','IIT Delhi','','html','verified'),
('IIT Delhi','startup','ecell-incubator','eDC student cell + FITT incubator (since 1999-2000).','https://edc.iitd.ac.in/','Entrepreneurship Development Cell','Student cell','','html','verified'),
('IIT Delhi','media','student','Board for Student Publications (BSP), electronic + print media body.','https://www.bspiitd.com/about','BSP IIT Delhi','Student media body','','html','verified'),
-- ── IIT Madras ──
('IIT Madras','placements','portal','Placement and Internship Office portal + brochures to 2024-25. No standalone annual report PDF; branch medians not in public PDFs.','https://placement.iitm.ac.in/','Placement and Internship Office','IIT Madras','','html','partial'),
('IIT Madras','rules','curricula','Academic curricula hub: BTech/Dual/MTech PDFs by batch year.','https://www.iitm.ac.in/academics/academic-curricula','Academic curricula','IIT Madras','','html','verified'),
('IIT Madras','fees','circular','Fees hub + per-sem institute/hostel circulars with SC/ST/PwD waiver table.','https://www.iitm.ac.in/academics/academic-services/fees','Fees hub','IIT Madras','2025-26','html','verified'),
('IIT Madras','support','diversity','ODEI + Be Happy wellness network + Womens Forum + student wellness report 2024.','https://odei.iitm.ac.in/index.html','Diversity Equity Inclusion','IIT Madras','','html','verified'),
('IIT Madras','startup','ecell-incubator','E-Cell + Nirmaan pre-incubator + IITM Incubation Cell (deep-tech).','https://incubation.iitm.ac.in/','Incubation Cell','IIT Madras','','html','verified'),
('IIT Madras','media','student','The Fifth Estate: official student media body, verified via Dean Students page.','https://www.t5eiitm.org/','The Fifth Estate','Student media body','','html','verified'),
-- ── IIT Kanpur ──
('IIT Kanpur','placements','portal','SPO portal + RAS. BTech numbers via press releases only (2024-25 UG 798/937 ~85%). No BTech report PDF; MBA reports only.','http://spo.iitk.ac.in/','Students Placement Office','IIT Kanpur SPO','2024-25','html','partial'),
('IIT Kanpur','rules','ug-manual','UG Manual v1.4 (20.07.2026): branch change after sem 2, grading, double major, dual load.','https://iitk.ac.in/doaa/data/UG_Manual_Version_1.4_20.07.2026.pdf','UG Manual v1.4','IIT Kanpur DoAA','2026-27','pdf','verified'),
('IIT Kanpur','fees','circular','DoSA cumulative fee structure with MEB/OEB slabs, SC/ST/PH waiver.','https://iitk.ac.in/dosa/data/Cumulative_Fee_Structure_For_Academic_Session_2025-2026-24-06-25.pdf','Fee structure 2025-26','IIT Kanpur DoSA','2025-26','pdf','verified'),
('IIT Kanpur','support','counselling','Centre for Mental Health and Wellbeing + Gender Cell + community welfare wings.','https://www.iitk.ac.in/counsel/','Counselling centre','IIT Kanpur','','html','verified'),
('IIT Kanpur','startup','ecell-incubator','E-Cell + SIIC incubator (est 2000, 500+ startups).','https://www.ecelliitk.org/index.html','E-Cell IIT Kanpur','Student cell','','html','verified'),
('IIT Kanpur','media','student','Vox Populi: student journalism body.','https://voxiitk.com/','Vox Populi','Student media body','','html','verified'),
-- ── IIT Kharagpur ──
('IIT Kharagpur','placements','portal','CDC portal. No public BTech report PDF; VGSoM MBA reports only. Branch medians not published.','https://cdc.iitkgp.ac.in/','Career Development Centre','IIT KGP CDC','','html','partial'),
('IIT Kharagpur','rules','ug-regulations','UG rules (Jan 2024): branch change Ch.9, interdisciplinary dual, attendance.','https://www.iitkgp.ac.in/assets/pdf/stu_ad.pdf','UG rules Jan 2024','IIT KGP','','pdf','verified'),
('IIT Kharagpur','fees','hub','Semester fees hub. Current BTech circular not surfaced; verify via Academic Section.','https://www.iitkgp.ac.in/semester_fees','Semester fees hub','IIT KGP','','html','missing'),
('IIT Kharagpur','support','counselling','SETU/Sarth counselling + inclusivity/PwD page + BCRoy hospital wellbeing.','https://sarth.iitkgp.ac.in/','SETU counselling','IIT KGP','','html','verified'),
('IIT Kharagpur','startup','ecell-incubator','E-Cell (est 2006) + STEP incubator (est 1986, oldest) + RMSoEE school.','https://stepiitkgp.org/','STEP incubator','IIT KGP','','html','verified'),
('IIT Kharagpur','media','student','Awaaz + Scholars Avenue: student-run publications.','https://www.awaaziitkgp.in/','Awaaz IIT KGP','Student media','','html','verified'),
-- ── IIT Roorkee ──
('IIT Roorkee','placements','portal','PIC portal. No BTech report PDF; MBA reports only. Branch medians not published.','https://pic.iitr.ac.in/','Placement and Internship Cell','IIT Roorkee PIC','','html','partial'),
('IIT Roorkee','rules','ug-ordinance','UG Ordinance BoG 2025: programmes, repeat, honours, BTech-MTech switch.','https://iitr.ac.in/Academics/static/Regulation/UG/UG_Ordinance_BoG_2025.pdf','UG Ordinance 2025','IIT Roorkee','2025','pdf','verified'),
('IIT Roorkee','fees','circular','Institute fees hub with UG 2026-27 PDF (Gen 1,55,550 autumn; SC/ST/PwD nil tuition).','https://iitr.ac.in/Academics/Institute%20Fees.html','Institute fees hub','IIT Roorkee','2026-27','html','verified'),
('IIT Roorkee','support','wellness','Wellness Centre + GATI gender + ICC committee.','http://wellness.iitr.ac.in/','Wellness Centre','IIT Roorkee','','html','verified'),
('IIT Roorkee','startup','ecell-incubator','E-Cell + TIDES incubator.','http://tides.iitr.ac.in/','TIDES incubator','IIT Roorkee','','html','verified'),
('IIT Roorkee','media','student','Watch Out: official student media body under Dean SRIC, since 1994.','https://watchout.iitr.ac.in/','Watch Out','Student media body','','html','verified'),
-- ── IIT Guwahati ──
('IIT Guwahati','placements','report','Placement reports hub with 2024-25 PDF: branch-wise median YES (CSE 34.1, ECE 23.43...).','https://iitg.ac.in/ccd/reports.html','CCD reports hub','IIT Guwahati CCD','2024-25','html','verified'),
('IIT Guwahati','rules','ordinance','Academic ordinance hub + academic affairs office.','https://iitg.ac.in/acad/academic_ordinance.php','Academic ordinance','IIT Guwahati','','html','verified'),
('IIT Guwahati','fees','circular','Fee hub + fresher UG fee PDF July 2026 intake.','https://www.iitg.ac.in/acad/admission/imp_info/fee.php','Fee hub','IIT Guwahati','2026-27','html','verified'),
('IIT Guwahati','support','diversity','Diversity Equality Office + Welfare Board counsellors.','https://www.iitg.ac.in/dec/index','Diversity office','IIT Guwahati','','html','verified'),
('IIT Guwahati','startup','ecell','E-Cell IIT Guwahati + UDGAM flagship. Incubator URL unverified.','https://www.ecelliitg.in/','E-Cell IIT Guwahati','Student cell','','html','partial'),
('IIT Guwahati','media','student','No independent student newspaper verified; official newsletter only.','https://iitgnewsletter.wixsite.com/iitgnewsletter/blog','IITG newsletter','Institute','','html','not_published'),
-- ── IIT Hyderabad ──
('IIT Hyderabad','placements','portal','OCS portal (JS app) with stats links + dept brochures. Branch median unconfirmed.','https://ocs.iith.ac.in/','OCS portal','IIT Hyderabad OCS','','html','partial'),
('IIT Hyderabad','rules','programmes','Programmes + forms hub. No single UG rulebook found.','https://iith.ac.in/academics/programmes-offered/','Programmes hub','IIT Hyderabad','','html','missing'),
('IIT Hyderabad','fees','circular','Fee structure hub with Jul-Dec 2026 PDF, new vs on-roll + foreign separate.','https://iith.ac.in/academics/fee-structure','Fee structure','IIT Hyderabad','2026-27','html','verified'),
('IIT Hyderabad','support','counselling','Sunshine counselling cell with 24/7 crisis numbers + peer mentors.','https://sunshine.iith.ac.in/','Sunshine','IIT Hyderabad','','html','verified'),
('IIT Hyderabad','startup','incubator','iTIC Foundation (DST-TBI, deep-tech) + IIC reports.','https://itic.iith.ac.in/','iTIC Foundation','IIT Hyderabad','','html','verified'),
('IIT Hyderabad','media','student','No independent student newspaper verified.','https://iith.ac.in/','IIT Hyderabad','Institute','','html','not_published'),
-- ── IIT (BHU) Varanasi ──
('IIT (BHU) Varanasi','placements','portal','TPO portal + dept brochures. No consolidated report PDF; branch medians not published.','https://www.placement.iitbhu.ac.in/','Training and Placement','IIT BHU TPO','','html','partial'),
('IIT (BHU) Varanasi','rules','ordinance','UG ordinances + appendices hub.','https://iitbhu.ac.in/dean/doaa/ordinances','Ordinances hub','IIT BHU DoAA','','html','verified'),
('IIT (BHU) Varanasi','fees','hub','Fee hub with 2026-27 onwards BTech/BPharm/BArch structures.','https://www.iitbhu.ac.in/dean/doaa/fee','Fee hub','IIT BHU DoAA','2026-27','html','verified'),
('IIT (BHU) Varanasi','support','counselling','Student Counselling Services in 2023-24 information booklet pp13-15.','https://iitbhu.ac.in/contents/institute/academics/fresher/doc/information_booket_2023-24.pdf','Fresher booklet 2023-24','IIT BHU','2023-24','pdf','partial'),
('IIT (BHU) Varanasi','startup','ecell-incubator','E-Cell + CIIE centre + I3 Foundation.','https://iitbhu.ac.in/cf/ciie','CIIE','IIT BHU','','html','verified'),
('IIT (BHU) Varanasi','media','student','No independent newspaper verified; Film and Media Council is a council.','https://iitbhu.ac.in/','IIT BHU','Institute','','html','not_published'),
-- ── IIT Indore ──
('IIT Indore','placements','portal','CAMC portal + 2026-27 brochure. Stats behind login; branch medians not public.','https://placement.iiti.ac.in/','Career Advancement Centre','IIT Indore CAMC','2026-27','html','partial'),
('IIT Indore','rules','ug-rules','UG Rules 08.06.2026 Final + curriculum/syllabi docs.','https://academic.iiti.ac.in/','Academic hub','IIT Indore','2026-27','html','verified'),
('IIT Indore','fees','circular','BTech 2025 batch 4-year tentative fee PDF.','https://academic.iiti.ac.in/Admission/2025/New/2025%20B.Tech.%20and%20B.Des.%20Batch_Four%20Year%20Fee%20Structure_Tentative.pdf','4-year fee tentative','IIT Indore','2025-26','pdf','verified'),
('IIT Indore','support','antiragging','Anti-ragging committee details published. Counselling/Gender/PwD URLs unverified.','https://www.iiti.ac.in/downloads/Anti-Ragging Committee Details.pdf','Anti-ragging details','IIT Indore','','pdf','partial'),
('IIT Indore','startup','ecell','E-Cell IIT Indore. Incubation centre URL unverified.','http://ecell.iiti.ac.in/','E-Cell','Student cell','','html','partial'),
('IIT Indore','media','student','No independent student newspaper verified.','https://www.iiti.ac.in/','IIT Indore','Institute','','html','not_published'),
-- ── IIT (ISM) Dhanbad ──
('IIT (ISM) Dhanbad','placements','report','CDC hub with 2025/2024/2023 PDFs: branch-wise median YES.','https://www.iitism.ac.in/placement-list','CDC placement list','IIT ISM CDC','2025','html','verified'),
('IIT (ISM) Dhanbad','rules','academics','Academics office hub. Single BTech ordinance PDF not located.','https://people.iitism.ac.in/~academics/','Academics office','IIT ISM','','html','missing'),
('IIT (ISM) Dhanbad','fees','circular','Fee structure hub + 2026-27 PDF (SC/ST/PwD nil tuition).','https://iitism.ac.in/fees-structure','Fee structure','IIT ISM','2026-27','html','verified'),
('IIT (ISM) Dhanbad','support','counselling','Student Counselling Centre + YourDOST online.','https://www.iitism.ac.in/counselling','Counselling centre','IIT ISM','','html','verified'),
('IIT (ISM) Dhanbad','startup','incubator','DIIE innovation/incubation/entrepreneurship + CIL centre.','https://diie.iitism.ac.in/','DIIE','IIT ISM','','html','verified'),
('IIT (ISM) Dhanbad','media','student','No independent student newspaper verified; institute corporate comms only.','https://people.iitism.ac.in/~inmedia','Institute media','Institute','','html','not_published'),
-- ── IIT Patna ──
('IIT Patna','placements','portal','CCDC portal: 2025-26 HTML highlights (avg 20.93, 1.3Cr, 90.88%); old 2021-22 PDF branch-wise.','https://ccdc.iitp.ac.in/','Career Development Centre','IIT Patna CCDC','2025-26','html','partial'),
('IIT Patna','rules','ordinance','BTech ordinances 2019 + courses/curriculum hub.','https://academics.iitp.ac.in/images/regulation/B.Tech_Ordinance_2019_onwards.pdf','BTech ordinance','IIT Patna','2019','pdf','verified'),
('IIT Patna','fees','circular','Fee structure hub July 2023 onwards + BTech fee PDF.','https://academics.iitp.ac.in/files/B.Tech_Fee.pdf','BTech fee','IIT Patna','2023-24','pdf','verified'),
('IIT Patna','support','gender','WGRC-ICC + hostel wardens + career counselling.','https://iitp.ac.in/miscellaneous/wgrc-icc','WGRC-ICC','IIT Patna','','html','verified'),
('IIT Patna','startup','incubator','IC IITP incubation centre (evidence in annual report). Portal URL unverified.','https://www.iitp.ac.in/','IIT Patna','Institute','','html','missing'),
('IIT Patna','media','student','No independent student newspaper verified.','https://www.iitp.ac.in/','IIT Patna','Institute','','html','not_published'),
-- ── IIT Gandhinagar ──
('IIT Gandhinagar','placements','portal','CDS portal + 2025-26 brochure. No public placement report PDF; branch medians not found.','https://cds.iitgn.ac.in/','Career Development Services','IITGN CDS','2025-26','html','partial'),
('IIT Gandhinagar','rules','curriculum','BTech curriculum hub (169-175 credits). Standalone UG rulebook not located.','https://iitgn.ac.in/academics/btech-curriculum','BTech curriculum','IITGN','','html','partial'),
('IIT Gandhinagar','fees','admissions','Admissions BTech hub. Dedicated fee PDF not surfaced via search.','https://iitgn.ac.in/admissions/btech','BTech admissions','IITGN','','html','missing'),
('IIT Gandhinagar','support','students','Students hub with well-being + hostel office. Cell deep links unverified.','https://iitgn.ac.in/students','Students hub','IITGN','','html','partial'),
('IIT Gandhinagar','startup','research-park','Research Park (90+ startups, 40+ companies). E-Cell URL unverified.','https://iitgnrp.com/','Research Park','IITGN','','html','partial'),
('IIT Gandhinagar','media','student','No independent student newspaper verified.','https://iitgn.ac.in/','IITGN','Institute','','html','not_published'),
-- ── IIT Mandi ──
('IIT Mandi','placements','report','CnP portal with 2025-26 placement+internship report PDF (sector-wise). Branch median unconfirmed.','https://students.iitmandi.ac.in/cnpcell','Career and Placement Cell','IIT Mandi CnP','2025-26','html','partial'),
('IIT Mandi','rules','ordinances','Ordinances hub: BTech/MA/MTech/PhD PDFs.','https://iitmandi.ac.in/ordinances','Ordinances hub','IIT Mandi','','html','verified'),
('IIT Mandi','fees','hub','Fees hub with ODD 2026-27 PDFs (new/existing/hostel-mess).','https://academics.iitmandi.ac.in/fees','Fees hub','IIT Mandi','2026-27','html','verified'),
('IIT Mandi','support','counselling','Counsellor + YourDOST/peer support via directory. Dedicated cell page unverified.','http://iitmandi.ac.in/directory','Directory','IIT Mandi','','html','partial'),
('IIT Mandi','startup','incubator','IIT Mandi Catalyst: HP first TBI (2016).','https://www.iitmandicatalyst.in/','Catalyst incubator','IIT Mandi','','html','verified'),
('IIT Mandi','media','student','No independent student newspaper verified.','https://www.iitmandi.ac.in/','IIT Mandi','Institute','','html','not_published'),
-- ── IIT Jodhpur ──
('IIT Jodhpur','placements','report','Stats portal + 2025 branch CTC PDF: branch-wise median YES.','https://spc.iitj.ac.in/placement-statistics','Placement statistics','IIT Jodhpur SPC','2025-26','html','verified'),
('IIT Jodhpur','rules','regulations','Academic regulations hub with UG 2025-26 + branch-change note.','https://iitj.ac.in/office-of-academics/en/academic-regulations','Academic regulations','IIT Jodhpur','','html','verified'),
('IIT Jodhpur','fees','circular','Fee structure hub + AY 2025-26 PDF.','https://iitj.ac.in/office-of-academics/en/fee-structure','Fee structure','IIT Jodhpur','2025-26','html','verified'),
('IIT Jodhpur','support','students','Hostels hub verified; cell deep links unverified.','https://www.iitj.ac.in/office-of-students/en/hostels','Hostels hub','IIT Jodhpur','','html','partial'),
('IIT Jodhpur','startup','incubator','Incubator/E-Cell URLs unverified in this pass.','https://www.iitj.ac.in/','IIT Jodhpur','Institute','','html','missing'),
('IIT Jodhpur','media','student','No independent student newspaper verified.','https://www.iitj.ac.in/','IIT Jodhpur','Institute','','html','not_published'),
-- ── IIT Ropar ──
('IIT Ropar','placements','report','CDPC portal with UG 2024-25 PDF (326 reg, 257 offers, avg 23.07, median 18). Branch medians unconfirmed.','https://placements.iitrpr.ac.in/','CDPC portal','IIT Ropar CDPC','2024-25','html','partial'),
('IIT Ropar','rules','curriculum','Curriculum hub + New BTech 2026 (160 credits). Standalone rulebook unverified.','https://www.iitrpr.ac.in/curriculum','Curriculum hub','IIT Ropar','','html','partial'),
('IIT Ropar','fees','hub','Fee structure hub with 4-year 2026 + 2025-26 PDFs.','https://www.iitrpr.ac.in/fee-structure','Fee structure','IIT Ropar','2026-27','html','verified'),
('IIT Ropar','support','cells','Counselling/ICC/Equal Opportunity/Womens Forum seen in footer; URLs unverified.','https://www.iitrpr.ac.in/','IIT Ropar','Institute','','html','partial'),
('IIT Ropar','startup','incubator','TBIF/Zone1 expected; URL unverified.','https://www.iitrpr.ac.in/','IIT Ropar','Institute','','html','missing'),
('IIT Ropar','media','student','No independent student newspaper verified.','https://www.iitrpr.ac.in/','IIT Ropar','Institute','','html','not_published'),
-- ── IIT Bhubaneswar ──
('IIT Bhubaneswar','placements','report','CDC + placement-2025 HTML table: branch-wise median YES (overall median 12).','https://www.iitbbs.ac.in/index.php/home/placement-2025','Placement 2025','IIT BBS CDC','2025','html','verified'),
('IIT Bhubaneswar','rules','regulations','Academics regulations hub. UG rulebook PDF unverified.','https://www.iitbbs.ac.in/index.php/home/academics','Academics hub','IIT BBS','','html','partial'),
('IIT Bhubaneswar','fees','circular','Fee structure hub + 2026-27 freshers PDF.','https://www.iitbbs.ac.in/index.php/home/academics/fee-structure','Fee structure','IIT BBS','2026-27','html','verified'),
('IIT Bhubaneswar','support','icc','ICC + student counselling centre + SC-ST-OBC cell.','https://www.iitbbs.ac.in/index.php/internal-complaints-committee-icc/','ICC','IIT BBS','','html','verified'),
('IIT Bhubaneswar','startup','incubator','Research and Entrepreneurship Park (60k sqft, 100 CUBE). E-Cell URL unverified.','https://rep.iitbbs.ac.in/','Research Park','IIT BBS','','html','partial'),
('IIT Bhubaneswar','media','student','Institute newsletter only; no independent student newspaper verified.','https://www.iitbbs.ac.in/index.php/media/iitbbs-express/','IITBBS Express','Institute','','html','not_published'),
-- ── IIT Jammu ──
('IIT Jammu','placements','report','CDS hub with 2025-26 PDF (3 Jun 2026) + 2023-24 (70.8%, 53LPA, 15.5avg). 2021-22 branch medians yes.','https://ww.iitjammu.ac.in/section/cds','Career Development Services','IIT Jammu CDS','2025-26','html','partial'),
('IIT Jammu','rules','hub','Rules hub unverified in this pass.','https://www.iitjammu.ac.in/','IIT Jammu','Institute','','html','missing'),
('IIT Jammu','fees','hub','Fee hub with BTech 2026 batch PDFs.','https://iitjammu.ac.in/fee','Fee hub','IIT Jammu','2026-27','html','verified'),
('IIT Jammu','support','cells','Anti-ragging/Equal Opportunity/SC-ST cells in footer; URLs unverified.','https://www.iitjammu.ac.in/','IIT Jammu','Institute','','html','partial'),
('IIT Jammu','startup','incubator','E-Cell/incubator URLs unverified.','https://www.iitjammu.ac.in/','IIT Jammu','Institute','','html','missing'),
('IIT Jammu','media','student','No independent student newspaper verified.','https://www.iitjammu.ac.in/','IIT Jammu','Institute','','html','not_published'),
-- ── IIT Tirupati ──
('IIT Tirupati','placements','portal','CDC portal + 2025-26 brochure via Drive. Branch median unknown.','https://cdc.iittp.ac.in/','Career Development Centre','IIT Tirupati CDC','2025-26','html','partial'),
('IIT Tirupati','rules','ordinances','Ordinances hub with BTech/MTech/Dual PDFs.','https://iittp.ac.in/ordinances','Ordinances hub','IIT Tirupati','','html','verified'),
('IIT Tirupati','fees','hub','Fee structure hub with Jan-Jun 2026 + 2025 PDFs.','https://www.iittp.ac.in/fee-structure','Fee structure','IIT Tirupati','2026','html','verified'),
('IIT Tirupati','support','counselling','GCU/Sarathi counselling + YourDOST 24/7 + hostel HoME.','https://sa.iittp.ac.in/gcu','Counselling unit','IIT Tirupati','','html','verified'),
('IIT Tirupati','startup','ecell','Student E-Cell + IIC + incubation policy PDF. Incubator portal unverified.','https://ecelliitt.in/','E-Cell','Student cell','','html','partial'),
('IIT Tirupati','media','student','Student Gymkhana verified; dedicated newspaper URL unverified.','https://sa.iittp.ac.in/','Student Gymkhana','Student body','','html','partial'),
-- ── IIT Palakkad ──
('IIT Palakkad','placements','report','CDC report 2024-25 PDF (203 cos, 153 offers, 52LPA highest, avg 13.24). Branch median no.','https://cdc.iitpkd.ac.in/sites/default/files/Placement%20report%202024-25.pdf','Placement report 2024-25','IIT Palakkad CDC','2024-25','pdf','partial'),
('IIT Palakkad','rules','programs','Programs hub: BTech regs 2022 + per-branch curricula.','https://iitpkd.ac.in/programs','Programs hub','IIT Palakkad','','html','verified'),
('IIT Palakkad','fees','circular','Fee hub with Aug-Nov 2025 + Aug-Dec 2026 BTech PDFs.','https://iitpkd.ac.in/details-fee-be-remitted','Fee hub','IIT Palakkad','2026-27','html','verified'),
('IIT Palakkad','support','hub','Hostels + clinic + wellness hub + grievance/anti-ragging in nav.','https://iitpkd.ac.in/hostels','Hostels hub','IIT Palakkad','','html','partial'),
('IIT Palakkad','startup','incubator','IPTIF Sec-8 TIH (73 startups). TECHIN portal + E-Cell URLs unverified.','https://iptif.tech/','IPTIF','IIT Palakkad','','html','partial'),
('IIT Palakkad','media','student','TFS student media body name in nav; URL unverified.','https://iitpkd.ac.in/','IIT Palakkad','Institute','','html','partial'),
-- ── IIT Bhilai ──
('IIT Bhilai','placements','report','CCPS report 2024-25 HTML: branch placed/% yes, branch median no (BTech ~15.1avg/12med).','https://www.iitbhilai.ac.in/index.php?pid=PlacementReport2024_2025','Placement report 2024-25','IIT Bhilai CCPS','2024-25','html','partial'),
('IIT Bhilai','rules','hub','Rulebook/faculty/curriculum hubs unverified; do not guess pid URLs.','https://www.iitbhilai.ac.in/','IIT Bhilai','Institute','','html','missing'),
('IIT Bhilai','fees','hub','Fee structure hub with 2026-27 BTech.','https://www.iitbhilai.ac.in/index.php?pid=fee_structure','Fee structure','IIT Bhilai','2026-27','html','verified'),
('IIT Bhilai','support','cells','OBC/anti-ragging/grievance in nav + Polaris student mentorship guides.','https://polaris.iitbhilai.ac.in/','Polaris guides','Student body','','html','partial'),
('IIT Bhilai','startup','incubator','No E-Cell/incubator URL verified (adm_ecell is e-Masters, not E-Cell).','https://www.iitbhilai.ac.in/','IIT Bhilai','Institute','','html','missing'),
('IIT Bhilai','media','student','Polaris student guides closest to media; no independent paper verified.','https://polaris.iitbhilai.ac.in/','Polaris','Student body','','html','partial'),
-- ── IIT Dharwad ──
('IIT Dharwad','placements','portal','CDC portal with live widget (2025-26 BTech 91.08%, 82LPA highest, 21.15avg). No report PDF; branch median no.','https://cdc.iitdh.ac.in/placement','CDC placement','IIT Dharwad CDC','2025-26','html','partial'),
('IIT Dharwad','rules','hub','Rulebook unverified; statutes/gazette only.','https://www.iitdh.ac.in/','IIT Dharwad','Institute','','html','missing'),
('IIT Dharwad','fees','circular','MS/MTech fee PDF pattern verified; BTech fee PDF unverified.','https://www.iitdh.ac.in/sites/default/files/2026-05/MS%20and%20M.Tech%20By%20Research.pdf','Fee example','IIT Dharwad','2026-27','pdf','partial'),
('IIT Dharwad','support','counselling','Counselling centre + Student Welfare Karune/Wellness (+91-81474-03386).','https://iitdh.ac.in/counselling-center','Counselling centre','IIT Dharwad','','html','verified'),
('IIT Dharwad','startup','incubator','dhaRti-BioNEST incubator + 2024 incubation call. E-Cell club unverified.','https://iitdharti.org/','dhaRti incubator','IIT Dharwad','','html','partial'),
('IIT Dharwad','media','student','No independent student newspaper verified.','https://www.iitdh.ac.in/','IIT Dharwad','Institute','','html','not_published'),
-- ── IIT Goa ──
('IIT Goa','placements','report','CDC portal live AY 2025-26 (BTech 116/107 92.24%) + 2021-2025 PDF: branch median YES.','https://iitgoa.ac.in/~placement/Placements.html','Placements live','IIT Goa CDC','2025-26','html','verified'),
('IIT Goa','rules','manual','UG Manual 13-02-2026 + MTech/PhD manuals hub.','https://iitgoa.ac.in/academic-rules-regulations','Academic rules','IIT Goa','2026','html','verified'),
('IIT Goa','fees','circular','BTech Autumn 2026-27 PDF.','https://iitgoa.ac.in/wp-content/uploads/B.Tech-Autumn-2026-27.pdf','BTech fee 2026-27','IIT Goa','2026-27','pdf','verified'),
('IIT Goa','support','dean','Dean Student Affairs + counsellor + hall office.','https://iitgoa.ac.in/student-affairs-dean/','Student affairs','IIT Goa','','html','verified'),
('IIT Goa','startup','incubator','E-Cell/incubator URLs unverified.','https://iitgoa.ac.in/','IIT Goa','Institute','','html','missing'),
('IIT Goa','media','student','No independent student newspaper verified.','https://iitgoa.ac.in/','IIT Goa','Institute','','html','not_published'),
-- ── JoSAA central ──
('JoSAA','counselling','business-rules','Business Rules 2026 PDF: supernumerary, Female-Only pool order, preparatory, de-reservation.','https://cdnbbsr.s3waas.gov.in/s313111c20aee51aeb480ecbd988cd8cc9/uploads/2026/06/20260601632081678.pdf','Business Rules 2026','JoSAA','2026','pdf','verified'),
('JoSAA','counselling','or-cr','OR-CR live query + archive (note spelling Archieve). P suffix = preparatory.','https://josaa.admissions.nic.in/applicant/SeatAllotmentResult/CurrentORCR.aspx','Current OR-CR','JoSAA','','html','verified'),
('JoSAA','counselling','seat-matrix','Seat matrix live query + archive hub.','https://josaa.admissions.nic.in/applicant/seatmatrix/seatmatrixinfo.aspx','Seat matrix','JoSAA','','html','verified'),
('JoSAA','counselling','top20','Top-20 percentile cutoffs hub, 2026 latest.','https://josaa.nic.in/top-20-percentile','Top-20 percentile','JoSAA','2026','html','verified')
;
