export type CollegeFactSeed = {
  institute: string;
  topic: string;
  subtype: string;
  claim: string;
  source_url: string;
  source_title: string;
  publisher: string;
  published_ay: string;
  format: string;
  coverage: string;
};

// Verified official sources only. Single source of truth for local fallback;
// same rows live in supabase/college-seed.sql for the database path.
export const collegeSeedFacts: CollegeFactSeed[] = [
  {
    "institute": "IIT Bombay",
    "topic": "placements",
    "subtype": "portal",
    "claim": "Placement portal with reports 2020-21 to 2023-24. No public branch-wise median table.",
    "source_url": "https://campus.placements.iitb.ac.in/",
    "source_title": "Placement Office portal",
    "publisher": "IIT Bombay Placement Office",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Bombay",
    "topic": "rules",
    "subtype": "ug-rulebook",
    "claim": "UG rulebook (June 2025): branch change, grading, minor/honors.",
    "source_url": "https://acad.iitb.ac.in/files/UG_RULE_BOOK.pdf",
    "source_title": "UG Rule Book",
    "publisher": "IIT Bombay Academic Office",
    "published_ay": "",
    "format": "pdf",
    "coverage": "verified"
  },
  {
    "institute": "IIT Bombay",
    "topic": "fees",
    "subtype": "circular",
    "claim": "Fee circulars hub: academic + hostel + remission OM, SC/ST/PwD tuition waiver pattern.",
    "source_url": "https://acad.iitb.ac.in/admissions/fees-structure",
    "source_title": "Fees structure hub",
    "publisher": "IIT Bombay Academic Office",
    "published_ay": "2026-27",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Bombay",
    "topic": "support",
    "subtype": "hub",
    "claim": "Support hub: SWC counselling, SC/ST, PwD, Gender Cell, hospital in one place.",
    "source_url": "https://dosa.iitb.ac.in/support-system",
    "source_title": "Support system",
    "publisher": "IIT Bombay Dean SA",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Bombay",
    "topic": "startup",
    "subtype": "ecell-incubator",
    "claim": "E-Cell (est 1998) + SINE incubator (TBI since 2004) + Desai Sethi School.",
    "source_url": "https://www.iitb.ac.in/industry/entrepreneurship",
    "source_title": "Entrepreneurship hub",
    "publisher": "IIT Bombay",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Bombay",
    "topic": "media",
    "subtype": "student",
    "claim": "Insight: official student media body, verified via gymkhana listing.",
    "source_url": "https://insightiitb.org/",
    "source_title": "Insight IIT Bombay",
    "publisher": "Student media body",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Delhi",
    "topic": "placements",
    "subtype": "portal",
    "claim": "OCS portal + press releases. No standalone BTech report PDF; MBA reports only. Branch-wise BTech not officially released.",
    "source_url": "http://ocs.iitd.ac.in/",
    "source_title": "Office of Career Services",
    "publisher": "IIT Delhi OCS",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Delhi",
    "topic": "rules",
    "subtype": "ug-rules",
    "claim": "UG Programme Rules + Curriculum 2025 hub (branch change CGPA 8.0/7.0, cap 115%).",
    "source_url": "https://home.iitd.ac.in/curriculum.php",
    "source_title": "Curriculum hub",
    "publisher": "IIT Delhi",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Delhi",
    "topic": "fees",
    "subtype": "circular",
    "claim": "Fee circulars hub incl UG Entry 2025-26; SC/ST/PwD 100% tuition waiver.",
    "source_url": "https://academics.iitd.ac.in/circulars",
    "source_title": "Circulars hub",
    "publisher": "IIT Delhi Academics",
    "published_ay": "2026-27",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Delhi",
    "topic": "support",
    "subtype": "diversity",
    "claim": "ODI diversity office: IGES gender unit, Indradhanu, OAE, BSW counselling.",
    "source_url": "https://odi.iitd.ac.in/ourTeam",
    "source_title": "Diversity and Inclusion",
    "publisher": "IIT Delhi",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Delhi",
    "topic": "startup",
    "subtype": "ecell-incubator",
    "claim": "eDC student cell + FITT incubator (since 1999-2000).",
    "source_url": "https://edc.iitd.ac.in/",
    "source_title": "Entrepreneurship Development Cell",
    "publisher": "Student cell",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Delhi",
    "topic": "media",
    "subtype": "student",
    "claim": "Board for Student Publications (BSP), electronic + print media body.",
    "source_url": "https://www.bspiitd.com/about",
    "source_title": "BSP IIT Delhi",
    "publisher": "Student media body",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Madras",
    "topic": "placements",
    "subtype": "portal",
    "claim": "Placement and Internship Office portal + brochures to 2024-25. No standalone annual report PDF; branch medians not in public PDFs.",
    "source_url": "https://placement.iitm.ac.in/",
    "source_title": "Placement and Internship Office",
    "publisher": "IIT Madras",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Madras",
    "topic": "rules",
    "subtype": "curricula",
    "claim": "Academic curricula hub: BTech/Dual/MTech PDFs by batch year.",
    "source_url": "https://www.iitm.ac.in/academics/academic-curricula",
    "source_title": "Academic curricula",
    "publisher": "IIT Madras",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Madras",
    "topic": "fees",
    "subtype": "circular",
    "claim": "Fees hub + per-sem institute/hostel circulars with SC/ST/PwD waiver table.",
    "source_url": "https://www.iitm.ac.in/academics/academic-services/fees",
    "source_title": "Fees hub",
    "publisher": "IIT Madras",
    "published_ay": "2025-26",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Madras",
    "topic": "support",
    "subtype": "diversity",
    "claim": "ODEI + Be Happy wellness network + Womens Forum + student wellness report 2024.",
    "source_url": "https://odei.iitm.ac.in/index.html",
    "source_title": "Diversity Equity Inclusion",
    "publisher": "IIT Madras",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Madras",
    "topic": "startup",
    "subtype": "ecell-incubator",
    "claim": "E-Cell + Nirmaan pre-incubator + IITM Incubation Cell (deep-tech).",
    "source_url": "https://incubation.iitm.ac.in/",
    "source_title": "Incubation Cell",
    "publisher": "IIT Madras",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Madras",
    "topic": "media",
    "subtype": "student",
    "claim": "The Fifth Estate: official student media body, verified via Dean Students page.",
    "source_url": "https://www.t5eiitm.org/",
    "source_title": "The Fifth Estate",
    "publisher": "Student media body",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Kanpur",
    "topic": "placements",
    "subtype": "portal",
    "claim": "SPO portal + RAS. BTech numbers via press releases only (2024-25 UG 798/937 ~85%). No BTech report PDF; MBA reports only.",
    "source_url": "http://spo.iitk.ac.in/",
    "source_title": "Students Placement Office",
    "publisher": "IIT Kanpur SPO",
    "published_ay": "2024-25",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Kanpur",
    "topic": "rules",
    "subtype": "ug-manual",
    "claim": "UG Manual v1.4 (20.07.2026): branch change after sem 2, grading, double major, dual load.",
    "source_url": "https://iitk.ac.in/doaa/data/UG_Manual_Version_1.4_20.07.2026.pdf",
    "source_title": "UG Manual v1.4",
    "publisher": "IIT Kanpur DoAA",
    "published_ay": "2026-27",
    "format": "pdf",
    "coverage": "verified"
  },
  {
    "institute": "IIT Kanpur",
    "topic": "fees",
    "subtype": "circular",
    "claim": "DoSA cumulative fee structure with MEB/OEB slabs, SC/ST/PH waiver.",
    "source_url": "https://iitk.ac.in/dosa/data/Cumulative_Fee_Structure_For_Academic_Session_2025-2026-24-06-25.pdf",
    "source_title": "Fee structure 2025-26",
    "publisher": "IIT Kanpur DoSA",
    "published_ay": "2025-26",
    "format": "pdf",
    "coverage": "verified"
  },
  {
    "institute": "IIT Kanpur",
    "topic": "support",
    "subtype": "counselling",
    "claim": "Centre for Mental Health and Wellbeing + Gender Cell + community welfare wings.",
    "source_url": "https://www.iitk.ac.in/counsel/",
    "source_title": "Counselling centre",
    "publisher": "IIT Kanpur",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Kanpur",
    "topic": "startup",
    "subtype": "ecell-incubator",
    "claim": "E-Cell + SIIC incubator (est 2000, 500+ startups).",
    "source_url": "https://www.ecelliitk.org/index.html",
    "source_title": "E-Cell IIT Kanpur",
    "publisher": "Student cell",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Kanpur",
    "topic": "media",
    "subtype": "student",
    "claim": "Vox Populi: student journalism body.",
    "source_url": "https://voxiitk.com/",
    "source_title": "Vox Populi",
    "publisher": "Student media body",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Kharagpur",
    "topic": "placements",
    "subtype": "portal",
    "claim": "CDC portal. No public BTech report PDF; VGSoM MBA reports only. Branch medians not published.",
    "source_url": "https://cdc.iitkgp.ac.in/",
    "source_title": "Career Development Centre",
    "publisher": "IIT KGP CDC",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Kharagpur",
    "topic": "rules",
    "subtype": "ug-regulations",
    "claim": "UG rules (Jan 2024): branch change Ch.9, interdisciplinary dual, attendance.",
    "source_url": "https://www.iitkgp.ac.in/assets/pdf/stu_ad.pdf",
    "source_title": "UG rules Jan 2024",
    "publisher": "IIT KGP",
    "published_ay": "",
    "format": "pdf",
    "coverage": "verified"
  },
  {
    "institute": "IIT Kharagpur",
    "topic": "fees",
    "subtype": "hub",
    "claim": "Semester fees hub. Current BTech circular not surfaced; verify via Academic Section.",
    "source_url": "https://www.iitkgp.ac.in/semester_fees",
    "source_title": "Semester fees hub",
    "publisher": "IIT KGP",
    "published_ay": "",
    "format": "html",
    "coverage": "missing"
  },
  {
    "institute": "IIT Kharagpur",
    "topic": "support",
    "subtype": "counselling",
    "claim": "SETU/Sarth counselling + inclusivity/PwD page + BCRoy hospital wellbeing.",
    "source_url": "https://sarth.iitkgp.ac.in/",
    "source_title": "SETU counselling",
    "publisher": "IIT KGP",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Kharagpur",
    "topic": "startup",
    "subtype": "ecell-incubator",
    "claim": "E-Cell (est 2006) + STEP incubator (est 1986, oldest) + RMSoEE school.",
    "source_url": "https://stepiitkgp.org/",
    "source_title": "STEP incubator",
    "publisher": "IIT KGP",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Kharagpur",
    "topic": "media",
    "subtype": "student",
    "claim": "Awaaz + Scholars Avenue: student-run publications.",
    "source_url": "https://www.awaaziitkgp.in/",
    "source_title": "Awaaz IIT KGP",
    "publisher": "Student media",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Roorkee",
    "topic": "placements",
    "subtype": "portal",
    "claim": "PIC portal. No BTech report PDF; MBA reports only. Branch medians not published.",
    "source_url": "https://pic.iitr.ac.in/",
    "source_title": "Placement and Internship Cell",
    "publisher": "IIT Roorkee PIC",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Roorkee",
    "topic": "rules",
    "subtype": "ug-ordinance",
    "claim": "UG Ordinance BoG 2025: programmes, repeat, honours, BTech-MTech switch.",
    "source_url": "https://iitr.ac.in/Academics/static/Regulation/UG/UG_Ordinance_BoG_2025.pdf",
    "source_title": "UG Ordinance 2025",
    "publisher": "IIT Roorkee",
    "published_ay": "2025",
    "format": "pdf",
    "coverage": "verified"
  },
  {
    "institute": "IIT Roorkee",
    "topic": "fees",
    "subtype": "circular",
    "claim": "Institute fees hub with UG 2026-27 PDF (Gen 1,55,550 autumn; SC/ST/PwD nil tuition).",
    "source_url": "https://iitr.ac.in/Academics/Institute%20Fees.html",
    "source_title": "Institute fees hub",
    "publisher": "IIT Roorkee",
    "published_ay": "2026-27",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Roorkee",
    "topic": "support",
    "subtype": "wellness",
    "claim": "Wellness Centre + GATI gender + ICC committee.",
    "source_url": "http://wellness.iitr.ac.in/",
    "source_title": "Wellness Centre",
    "publisher": "IIT Roorkee",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Roorkee",
    "topic": "startup",
    "subtype": "ecell-incubator",
    "claim": "E-Cell + TIDES incubator.",
    "source_url": "http://tides.iitr.ac.in/",
    "source_title": "TIDES incubator",
    "publisher": "IIT Roorkee",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Roorkee",
    "topic": "media",
    "subtype": "student",
    "claim": "Watch Out: official student media body under Dean SRIC, since 1994.",
    "source_url": "https://watchout.iitr.ac.in/",
    "source_title": "Watch Out",
    "publisher": "Student media body",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Guwahati",
    "topic": "placements",
    "subtype": "report",
    "claim": "Placement reports hub with 2024-25 PDF: branch-wise median YES (CSE 34.1, ECE 23.43...).",
    "source_url": "https://iitg.ac.in/ccd/reports.html",
    "source_title": "CCD reports hub",
    "publisher": "IIT Guwahati CCD",
    "published_ay": "2024-25",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Guwahati",
    "topic": "rules",
    "subtype": "ordinance",
    "claim": "Academic ordinance hub + academic affairs office.",
    "source_url": "https://iitg.ac.in/acad/academic_ordinance.php",
    "source_title": "Academic ordinance",
    "publisher": "IIT Guwahati",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Guwahati",
    "topic": "fees",
    "subtype": "circular",
    "claim": "Fee hub + fresher UG fee PDF July 2026 intake.",
    "source_url": "https://www.iitg.ac.in/acad/admission/imp_info/fee.php",
    "source_title": "Fee hub",
    "publisher": "IIT Guwahati",
    "published_ay": "2026-27",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Guwahati",
    "topic": "support",
    "subtype": "diversity",
    "claim": "Diversity Equality Office + Welfare Board counsellors.",
    "source_url": "https://www.iitg.ac.in/dec/index",
    "source_title": "Diversity office",
    "publisher": "IIT Guwahati",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Guwahati",
    "topic": "startup",
    "subtype": "ecell",
    "claim": "E-Cell IIT Guwahati + UDGAM flagship. Incubator URL unverified.",
    "source_url": "https://www.ecelliitg.in/",
    "source_title": "E-Cell IIT Guwahati",
    "publisher": "Student cell",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Guwahati",
    "topic": "media",
    "subtype": "student",
    "claim": "No independent student newspaper verified; official newsletter only.",
    "source_url": "https://iitgnewsletter.wixsite.com/iitgnewsletter/blog",
    "source_title": "IITG newsletter",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "not_published"
  },
  {
    "institute": "IIT Hyderabad",
    "topic": "placements",
    "subtype": "portal",
    "claim": "OCS portal (JS app) with stats links + dept brochures. Branch median unconfirmed.",
    "source_url": "https://ocs.iith.ac.in/",
    "source_title": "OCS portal",
    "publisher": "IIT Hyderabad OCS",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Hyderabad",
    "topic": "rules",
    "subtype": "programmes",
    "claim": "Programmes + forms hub. No single UG rulebook found.",
    "source_url": "https://iith.ac.in/academics/programmes-offered/",
    "source_title": "Programmes hub",
    "publisher": "IIT Hyderabad",
    "published_ay": "",
    "format": "html",
    "coverage": "missing"
  },
  {
    "institute": "IIT Hyderabad",
    "topic": "fees",
    "subtype": "circular",
    "claim": "Fee structure hub with Jul-Dec 2026 PDF, new vs on-roll + foreign separate.",
    "source_url": "https://iith.ac.in/academics/fee-structure",
    "source_title": "Fee structure",
    "publisher": "IIT Hyderabad",
    "published_ay": "2026-27",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Hyderabad",
    "topic": "support",
    "subtype": "counselling",
    "claim": "Sunshine counselling cell with 24/7 crisis numbers + peer mentors.",
    "source_url": "https://sunshine.iith.ac.in/",
    "source_title": "Sunshine",
    "publisher": "IIT Hyderabad",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Hyderabad",
    "topic": "startup",
    "subtype": "incubator",
    "claim": "iTIC Foundation (DST-TBI, deep-tech) + IIC reports.",
    "source_url": "https://itic.iith.ac.in/",
    "source_title": "iTIC Foundation",
    "publisher": "IIT Hyderabad",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Hyderabad",
    "topic": "media",
    "subtype": "student",
    "claim": "No independent student newspaper verified.",
    "source_url": "https://iith.ac.in/",
    "source_title": "IIT Hyderabad",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "not_published"
  },
  {
    "institute": "IIT (BHU) Varanasi",
    "topic": "placements",
    "subtype": "portal",
    "claim": "TPO portal + dept brochures. No consolidated report PDF; branch medians not published.",
    "source_url": "https://www.placement.iitbhu.ac.in/",
    "source_title": "Training and Placement",
    "publisher": "IIT BHU TPO",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT (BHU) Varanasi",
    "topic": "rules",
    "subtype": "ordinance",
    "claim": "UG ordinances + appendices hub.",
    "source_url": "https://iitbhu.ac.in/dean/doaa/ordinances",
    "source_title": "Ordinances hub",
    "publisher": "IIT BHU DoAA",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT (BHU) Varanasi",
    "topic": "fees",
    "subtype": "hub",
    "claim": "Fee hub with 2026-27 onwards BTech/BPharm/BArch structures.",
    "source_url": "https://www.iitbhu.ac.in/dean/doaa/fee",
    "source_title": "Fee hub",
    "publisher": "IIT BHU DoAA",
    "published_ay": "2026-27",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT (BHU) Varanasi",
    "topic": "support",
    "subtype": "counselling",
    "claim": "Student Counselling Services in 2023-24 information booklet pp13-15.",
    "source_url": "https://iitbhu.ac.in/contents/institute/academics/fresher/doc/information_booket_2023-24.pdf",
    "source_title": "Fresher booklet 2023-24",
    "publisher": "IIT BHU",
    "published_ay": "2023-24",
    "format": "pdf",
    "coverage": "partial"
  },
  {
    "institute": "IIT (BHU) Varanasi",
    "topic": "startup",
    "subtype": "ecell-incubator",
    "claim": "E-Cell + CIIE centre + I3 Foundation.",
    "source_url": "https://iitbhu.ac.in/cf/ciie",
    "source_title": "CIIE",
    "publisher": "IIT BHU",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT (BHU) Varanasi",
    "topic": "media",
    "subtype": "student",
    "claim": "No independent newspaper verified; Film and Media Council is a council.",
    "source_url": "https://iitbhu.ac.in/",
    "source_title": "IIT BHU",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "not_published"
  },
  {
    "institute": "IIT Indore",
    "topic": "placements",
    "subtype": "portal",
    "claim": "CAMC portal + 2026-27 brochure. Stats behind login; branch medians not public.",
    "source_url": "https://placement.iiti.ac.in/",
    "source_title": "Career Advancement Centre",
    "publisher": "IIT Indore CAMC",
    "published_ay": "2026-27",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Indore",
    "topic": "rules",
    "subtype": "ug-rules",
    "claim": "UG Rules 08.06.2026 Final + curriculum/syllabi docs.",
    "source_url": "https://academic.iiti.ac.in/",
    "source_title": "Academic hub",
    "publisher": "IIT Indore",
    "published_ay": "2026-27",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Indore",
    "topic": "fees",
    "subtype": "circular",
    "claim": "BTech 2025 batch 4-year tentative fee PDF.",
    "source_url": "https://academic.iiti.ac.in/Admission/2025/New/2025%20B.Tech.%20and%20B.Des.%20Batch_Four%20Year%20Fee%20Structure_Tentative.pdf",
    "source_title": "4-year fee tentative",
    "publisher": "IIT Indore",
    "published_ay": "2025-26",
    "format": "pdf",
    "coverage": "verified"
  },
  {
    "institute": "IIT Indore",
    "topic": "support",
    "subtype": "antiragging",
    "claim": "Anti-ragging committee details published. Counselling/Gender/PwD URLs unverified.",
    "source_url": "https://www.iiti.ac.in/downloads/Anti-Ragging Committee Details.pdf",
    "source_title": "Anti-ragging details",
    "publisher": "IIT Indore",
    "published_ay": "",
    "format": "pdf",
    "coverage": "partial"
  },
  {
    "institute": "IIT Indore",
    "topic": "startup",
    "subtype": "ecell",
    "claim": "E-Cell IIT Indore. Incubation centre URL unverified.",
    "source_url": "http://ecell.iiti.ac.in/",
    "source_title": "E-Cell",
    "publisher": "Student cell",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Indore",
    "topic": "media",
    "subtype": "student",
    "claim": "No independent student newspaper verified.",
    "source_url": "https://www.iiti.ac.in/",
    "source_title": "IIT Indore",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "not_published"
  },
  {
    "institute": "IIT (ISM) Dhanbad",
    "topic": "placements",
    "subtype": "report",
    "claim": "CDC hub with 2025/2024/2023 PDFs: branch-wise median YES.",
    "source_url": "https://www.iitism.ac.in/placement-list",
    "source_title": "CDC placement list",
    "publisher": "IIT ISM CDC",
    "published_ay": "2025",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT (ISM) Dhanbad",
    "topic": "rules",
    "subtype": "academics",
    "claim": "Academics office hub. Single BTech ordinance PDF not located.",
    "source_url": "https://people.iitism.ac.in/~academics/",
    "source_title": "Academics office",
    "publisher": "IIT ISM",
    "published_ay": "",
    "format": "html",
    "coverage": "missing"
  },
  {
    "institute": "IIT (ISM) Dhanbad",
    "topic": "fees",
    "subtype": "circular",
    "claim": "Fee structure hub + 2026-27 PDF (SC/ST/PwD nil tuition).",
    "source_url": "https://iitism.ac.in/fees-structure",
    "source_title": "Fee structure",
    "publisher": "IIT ISM",
    "published_ay": "2026-27",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT (ISM) Dhanbad",
    "topic": "support",
    "subtype": "counselling",
    "claim": "Student Counselling Centre + YourDOST online.",
    "source_url": "https://www.iitism.ac.in/counselling",
    "source_title": "Counselling centre",
    "publisher": "IIT ISM",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT (ISM) Dhanbad",
    "topic": "startup",
    "subtype": "incubator",
    "claim": "DIIE innovation/incubation/entrepreneurship + CIL centre.",
    "source_url": "https://diie.iitism.ac.in/",
    "source_title": "DIIE",
    "publisher": "IIT ISM",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT (ISM) Dhanbad",
    "topic": "media",
    "subtype": "student",
    "claim": "No independent student newspaper verified; institute corporate comms only.",
    "source_url": "https://people.iitism.ac.in/~inmedia",
    "source_title": "Institute media",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "not_published"
  },
  {
    "institute": "IIT Patna",
    "topic": "placements",
    "subtype": "portal",
    "claim": "CCDC portal: 2025-26 HTML highlights (avg 20.93, 1.3Cr, 90.88%); old 2021-22 PDF branch-wise.",
    "source_url": "https://ccdc.iitp.ac.in/",
    "source_title": "Career Development Centre",
    "publisher": "IIT Patna CCDC",
    "published_ay": "2025-26",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Patna",
    "topic": "rules",
    "subtype": "ordinance",
    "claim": "BTech ordinances 2019 + courses/curriculum hub.",
    "source_url": "https://academics.iitp.ac.in/images/regulation/B.Tech_Ordinance_2019_onwards.pdf",
    "source_title": "BTech ordinance",
    "publisher": "IIT Patna",
    "published_ay": "2019",
    "format": "pdf",
    "coverage": "verified"
  },
  {
    "institute": "IIT Patna",
    "topic": "fees",
    "subtype": "circular",
    "claim": "Fee structure hub July 2023 onwards + BTech fee PDF.",
    "source_url": "https://academics.iitp.ac.in/files/B.Tech_Fee.pdf",
    "source_title": "BTech fee",
    "publisher": "IIT Patna",
    "published_ay": "2023-24",
    "format": "pdf",
    "coverage": "verified"
  },
  {
    "institute": "IIT Patna",
    "topic": "support",
    "subtype": "gender",
    "claim": "WGRC-ICC + hostel wardens + career counselling.",
    "source_url": "https://iitp.ac.in/miscellaneous/wgrc-icc",
    "source_title": "WGRC-ICC",
    "publisher": "IIT Patna",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Patna",
    "topic": "startup",
    "subtype": "incubator",
    "claim": "IC IITP incubation centre (evidence in annual report). Portal URL unverified.",
    "source_url": "https://www.iitp.ac.in/",
    "source_title": "IIT Patna",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "missing"
  },
  {
    "institute": "IIT Patna",
    "topic": "media",
    "subtype": "student",
    "claim": "No independent student newspaper verified.",
    "source_url": "https://www.iitp.ac.in/",
    "source_title": "IIT Patna",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "not_published"
  },
  {
    "institute": "IIT Gandhinagar",
    "topic": "placements",
    "subtype": "portal",
    "claim": "CDS portal + 2025-26 brochure. No public placement report PDF; branch medians not found.",
    "source_url": "https://cds.iitgn.ac.in/",
    "source_title": "Career Development Services",
    "publisher": "IITGN CDS",
    "published_ay": "2025-26",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Gandhinagar",
    "topic": "rules",
    "subtype": "curriculum",
    "claim": "BTech curriculum hub (169-175 credits). Standalone UG rulebook not located.",
    "source_url": "https://iitgn.ac.in/academics/btech-curriculum",
    "source_title": "BTech curriculum",
    "publisher": "IITGN",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Gandhinagar",
    "topic": "fees",
    "subtype": "admissions",
    "claim": "Admissions BTech hub. Dedicated fee PDF not surfaced via search.",
    "source_url": "https://iitgn.ac.in/admissions/btech",
    "source_title": "BTech admissions",
    "publisher": "IITGN",
    "published_ay": "",
    "format": "html",
    "coverage": "missing"
  },
  {
    "institute": "IIT Gandhinagar",
    "topic": "support",
    "subtype": "students",
    "claim": "Students hub with well-being + hostel office. Cell deep links unverified.",
    "source_url": "https://iitgn.ac.in/students",
    "source_title": "Students hub",
    "publisher": "IITGN",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Gandhinagar",
    "topic": "startup",
    "subtype": "research-park",
    "claim": "Research Park (90+ startups, 40+ companies). E-Cell URL unverified.",
    "source_url": "https://iitgnrp.com/",
    "source_title": "Research Park",
    "publisher": "IITGN",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Gandhinagar",
    "topic": "media",
    "subtype": "student",
    "claim": "No independent student newspaper verified.",
    "source_url": "https://iitgn.ac.in/",
    "source_title": "IITGN",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "not_published"
  },
  {
    "institute": "IIT Mandi",
    "topic": "placements",
    "subtype": "report",
    "claim": "CnP portal with 2025-26 placement+internship report PDF (sector-wise). Branch median unconfirmed.",
    "source_url": "https://students.iitmandi.ac.in/cnpcell",
    "source_title": "Career and Placement Cell",
    "publisher": "IIT Mandi CnP",
    "published_ay": "2025-26",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Mandi",
    "topic": "rules",
    "subtype": "ordinances",
    "claim": "Ordinances hub: BTech/MA/MTech/PhD PDFs.",
    "source_url": "https://iitmandi.ac.in/ordinances",
    "source_title": "Ordinances hub",
    "publisher": "IIT Mandi",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Mandi",
    "topic": "fees",
    "subtype": "hub",
    "claim": "Fees hub with ODD 2026-27 PDFs (new/existing/hostel-mess).",
    "source_url": "https://academics.iitmandi.ac.in/fees",
    "source_title": "Fees hub",
    "publisher": "IIT Mandi",
    "published_ay": "2026-27",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Mandi",
    "topic": "support",
    "subtype": "counselling",
    "claim": "Counsellor + YourDOST/peer support via directory. Dedicated cell page unverified.",
    "source_url": "http://iitmandi.ac.in/directory",
    "source_title": "Directory",
    "publisher": "IIT Mandi",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Mandi",
    "topic": "startup",
    "subtype": "incubator",
    "claim": "IIT Mandi Catalyst: HP first TBI (2016).",
    "source_url": "https://www.iitmandicatalyst.in/",
    "source_title": "Catalyst incubator",
    "publisher": "IIT Mandi",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Mandi",
    "topic": "media",
    "subtype": "student",
    "claim": "No independent student newspaper verified.",
    "source_url": "https://www.iitmandi.ac.in/",
    "source_title": "IIT Mandi",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "not_published"
  },
  {
    "institute": "IIT Jodhpur",
    "topic": "placements",
    "subtype": "report",
    "claim": "Stats portal + 2025 branch CTC PDF: branch-wise median YES.",
    "source_url": "https://spc.iitj.ac.in/placement-statistics",
    "source_title": "Placement statistics",
    "publisher": "IIT Jodhpur SPC",
    "published_ay": "2025-26",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Jodhpur",
    "topic": "rules",
    "subtype": "regulations",
    "claim": "Academic regulations hub with UG 2025-26 + branch-change note.",
    "source_url": "https://iitj.ac.in/office-of-academics/en/academic-regulations",
    "source_title": "Academic regulations",
    "publisher": "IIT Jodhpur",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Jodhpur",
    "topic": "fees",
    "subtype": "circular",
    "claim": "Fee structure hub + AY 2025-26 PDF.",
    "source_url": "https://iitj.ac.in/office-of-academics/en/fee-structure",
    "source_title": "Fee structure",
    "publisher": "IIT Jodhpur",
    "published_ay": "2025-26",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Jodhpur",
    "topic": "support",
    "subtype": "students",
    "claim": "Hostels hub verified; cell deep links unverified.",
    "source_url": "https://www.iitj.ac.in/office-of-students/en/hostels",
    "source_title": "Hostels hub",
    "publisher": "IIT Jodhpur",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Jodhpur",
    "topic": "startup",
    "subtype": "incubator",
    "claim": "Incubator/E-Cell URLs unverified in this pass.",
    "source_url": "https://www.iitj.ac.in/",
    "source_title": "IIT Jodhpur",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "missing"
  },
  {
    "institute": "IIT Jodhpur",
    "topic": "media",
    "subtype": "student",
    "claim": "No independent student newspaper verified.",
    "source_url": "https://www.iitj.ac.in/",
    "source_title": "IIT Jodhpur",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "not_published"
  },
  {
    "institute": "IIT Ropar",
    "topic": "placements",
    "subtype": "report",
    "claim": "CDPC portal with UG 2024-25 PDF (326 reg, 257 offers, avg 23.07, median 18). Branch medians unconfirmed.",
    "source_url": "https://placements.iitrpr.ac.in/",
    "source_title": "CDPC portal",
    "publisher": "IIT Ropar CDPC",
    "published_ay": "2024-25",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Ropar",
    "topic": "rules",
    "subtype": "curriculum",
    "claim": "Curriculum hub + New BTech 2026 (160 credits). Standalone rulebook unverified.",
    "source_url": "https://www.iitrpr.ac.in/curriculum",
    "source_title": "Curriculum hub",
    "publisher": "IIT Ropar",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Ropar",
    "topic": "fees",
    "subtype": "hub",
    "claim": "Fee structure hub with 4-year 2026 + 2025-26 PDFs.",
    "source_url": "https://www.iitrpr.ac.in/fee-structure",
    "source_title": "Fee structure",
    "publisher": "IIT Ropar",
    "published_ay": "2026-27",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Ropar",
    "topic": "support",
    "subtype": "cells",
    "claim": "Counselling/ICC/Equal Opportunity/Womens Forum seen in footer; URLs unverified.",
    "source_url": "https://www.iitrpr.ac.in/",
    "source_title": "IIT Ropar",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Ropar",
    "topic": "startup",
    "subtype": "incubator",
    "claim": "TBIF/Zone1 expected; URL unverified.",
    "source_url": "https://www.iitrpr.ac.in/",
    "source_title": "IIT Ropar",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "missing"
  },
  {
    "institute": "IIT Ropar",
    "topic": "media",
    "subtype": "student",
    "claim": "No independent student newspaper verified.",
    "source_url": "https://www.iitrpr.ac.in/",
    "source_title": "IIT Ropar",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "not_published"
  },
  {
    "institute": "IIT Bhubaneswar",
    "topic": "placements",
    "subtype": "report",
    "claim": "CDC + placement-2025 HTML table: branch-wise median YES (overall median 12).",
    "source_url": "https://www.iitbbs.ac.in/index.php/home/placement-2025",
    "source_title": "Placement 2025",
    "publisher": "IIT BBS CDC",
    "published_ay": "2025",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Bhubaneswar",
    "topic": "rules",
    "subtype": "regulations",
    "claim": "Academics regulations hub. UG rulebook PDF unverified.",
    "source_url": "https://www.iitbbs.ac.in/index.php/home/academics",
    "source_title": "Academics hub",
    "publisher": "IIT BBS",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Bhubaneswar",
    "topic": "fees",
    "subtype": "circular",
    "claim": "Fee structure hub + 2026-27 freshers PDF.",
    "source_url": "https://www.iitbbs.ac.in/index.php/home/academics/fee-structure",
    "source_title": "Fee structure",
    "publisher": "IIT BBS",
    "published_ay": "2026-27",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Bhubaneswar",
    "topic": "support",
    "subtype": "icc",
    "claim": "ICC + student counselling centre + SC-ST-OBC cell.",
    "source_url": "https://www.iitbbs.ac.in/index.php/internal-complaints-committee-icc/",
    "source_title": "ICC",
    "publisher": "IIT BBS",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Bhubaneswar",
    "topic": "startup",
    "subtype": "incubator",
    "claim": "Research and Entrepreneurship Park (60k sqft, 100 CUBE). E-Cell URL unverified.",
    "source_url": "https://rep.iitbbs.ac.in/",
    "source_title": "Research Park",
    "publisher": "IIT BBS",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Bhubaneswar",
    "topic": "media",
    "subtype": "student",
    "claim": "Institute newsletter only; no independent student newspaper verified.",
    "source_url": "https://www.iitbbs.ac.in/index.php/media/iitbbs-express/",
    "source_title": "IITBBS Express",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "not_published"
  },
  {
    "institute": "IIT Jammu",
    "topic": "placements",
    "subtype": "report",
    "claim": "CDS hub with 2025-26 PDF (3 Jun 2026) + 2023-24 (70.8%, 53LPA, 15.5avg). 2021-22 branch medians yes.",
    "source_url": "https://ww.iitjammu.ac.in/section/cds",
    "source_title": "Career Development Services",
    "publisher": "IIT Jammu CDS",
    "published_ay": "2025-26",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Jammu",
    "topic": "rules",
    "subtype": "hub",
    "claim": "Rules hub unverified in this pass.",
    "source_url": "https://www.iitjammu.ac.in/",
    "source_title": "IIT Jammu",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "missing"
  },
  {
    "institute": "IIT Jammu",
    "topic": "fees",
    "subtype": "hub",
    "claim": "Fee hub with BTech 2026 batch PDFs.",
    "source_url": "https://iitjammu.ac.in/fee",
    "source_title": "Fee hub",
    "publisher": "IIT Jammu",
    "published_ay": "2026-27",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Jammu",
    "topic": "support",
    "subtype": "cells",
    "claim": "Anti-ragging/Equal Opportunity/SC-ST cells in footer; URLs unverified.",
    "source_url": "https://www.iitjammu.ac.in/",
    "source_title": "IIT Jammu",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Jammu",
    "topic": "startup",
    "subtype": "incubator",
    "claim": "E-Cell/incubator URLs unverified.",
    "source_url": "https://www.iitjammu.ac.in/",
    "source_title": "IIT Jammu",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "missing"
  },
  {
    "institute": "IIT Jammu",
    "topic": "media",
    "subtype": "student",
    "claim": "No independent student newspaper verified.",
    "source_url": "https://www.iitjammu.ac.in/",
    "source_title": "IIT Jammu",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "not_published"
  },
  {
    "institute": "IIT Tirupati",
    "topic": "placements",
    "subtype": "portal",
    "claim": "CDC portal + 2025-26 brochure via Drive. Branch median unknown.",
    "source_url": "https://cdc.iittp.ac.in/",
    "source_title": "Career Development Centre",
    "publisher": "IIT Tirupati CDC",
    "published_ay": "2025-26",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Tirupati",
    "topic": "rules",
    "subtype": "ordinances",
    "claim": "Ordinances hub with BTech/MTech/Dual PDFs.",
    "source_url": "https://iittp.ac.in/ordinances",
    "source_title": "Ordinances hub",
    "publisher": "IIT Tirupati",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Tirupati",
    "topic": "fees",
    "subtype": "hub",
    "claim": "Fee structure hub with Jan-Jun 2026 + 2025 PDFs.",
    "source_url": "https://www.iittp.ac.in/fee-structure",
    "source_title": "Fee structure",
    "publisher": "IIT Tirupati",
    "published_ay": "2026",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Tirupati",
    "topic": "support",
    "subtype": "counselling",
    "claim": "GCU/Sarathi counselling + YourDOST 24/7 + hostel HoME.",
    "source_url": "https://sa.iittp.ac.in/gcu",
    "source_title": "Counselling unit",
    "publisher": "IIT Tirupati",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Tirupati",
    "topic": "startup",
    "subtype": "ecell",
    "claim": "Student E-Cell + IIC + incubation policy PDF. Incubator portal unverified.",
    "source_url": "https://ecelliitt.in/",
    "source_title": "E-Cell",
    "publisher": "Student cell",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Tirupati",
    "topic": "media",
    "subtype": "student",
    "claim": "Student Gymkhana verified; dedicated newspaper URL unverified.",
    "source_url": "https://sa.iittp.ac.in/",
    "source_title": "Student Gymkhana",
    "publisher": "Student body",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Palakkad",
    "topic": "placements",
    "subtype": "report",
    "claim": "CDC report 2024-25 PDF (203 cos, 153 offers, 52LPA highest, avg 13.24). Branch median no.",
    "source_url": "https://cdc.iitpkd.ac.in/sites/default/files/Placement%20report%202024-25.pdf",
    "source_title": "Placement report 2024-25",
    "publisher": "IIT Palakkad CDC",
    "published_ay": "2024-25",
    "format": "pdf",
    "coverage": "partial"
  },
  {
    "institute": "IIT Palakkad",
    "topic": "rules",
    "subtype": "programs",
    "claim": "Programs hub: BTech regs 2022 + per-branch curricula.",
    "source_url": "https://iitpkd.ac.in/programs",
    "source_title": "Programs hub",
    "publisher": "IIT Palakkad",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Palakkad",
    "topic": "fees",
    "subtype": "circular",
    "claim": "Fee hub with Aug-Nov 2025 + Aug-Dec 2026 BTech PDFs.",
    "source_url": "https://iitpkd.ac.in/details-fee-be-remitted",
    "source_title": "Fee hub",
    "publisher": "IIT Palakkad",
    "published_ay": "2026-27",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Palakkad",
    "topic": "support",
    "subtype": "hub",
    "claim": "Hostels + clinic + wellness hub + grievance/anti-ragging in nav.",
    "source_url": "https://iitpkd.ac.in/hostels",
    "source_title": "Hostels hub",
    "publisher": "IIT Palakkad",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Palakkad",
    "topic": "startup",
    "subtype": "incubator",
    "claim": "IPTIF Sec-8 TIH (73 startups). TECHIN portal + E-Cell URLs unverified.",
    "source_url": "https://iptif.tech/",
    "source_title": "IPTIF",
    "publisher": "IIT Palakkad",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Palakkad",
    "topic": "media",
    "subtype": "student",
    "claim": "TFS student media body name in nav; URL unverified.",
    "source_url": "https://iitpkd.ac.in/",
    "source_title": "IIT Palakkad",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Bhilai",
    "topic": "placements",
    "subtype": "report",
    "claim": "CCPS report 2024-25 HTML: branch placed/% yes, branch median no (BTech ~15.1avg/12med).",
    "source_url": "https://www.iitbhilai.ac.in/index.php?pid=PlacementReport2024_2025",
    "source_title": "Placement report 2024-25",
    "publisher": "IIT Bhilai CCPS",
    "published_ay": "2024-25",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Bhilai",
    "topic": "rules",
    "subtype": "hub",
    "claim": "Rulebook/faculty/curriculum hubs unverified; do not guess pid URLs.",
    "source_url": "https://www.iitbhilai.ac.in/",
    "source_title": "IIT Bhilai",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "missing"
  },
  {
    "institute": "IIT Bhilai",
    "topic": "fees",
    "subtype": "hub",
    "claim": "Fee structure hub with 2026-27 BTech.",
    "source_url": "https://www.iitbhilai.ac.in/index.php?pid=fee_structure",
    "source_title": "Fee structure",
    "publisher": "IIT Bhilai",
    "published_ay": "2026-27",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Bhilai",
    "topic": "support",
    "subtype": "cells",
    "claim": "OBC/anti-ragging/grievance in nav + Polaris student mentorship guides.",
    "source_url": "https://polaris.iitbhilai.ac.in/",
    "source_title": "Polaris guides",
    "publisher": "Student body",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Bhilai",
    "topic": "startup",
    "subtype": "incubator",
    "claim": "No E-Cell/incubator URL verified (adm_ecell is e-Masters, not E-Cell).",
    "source_url": "https://www.iitbhilai.ac.in/",
    "source_title": "IIT Bhilai",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "missing"
  },
  {
    "institute": "IIT Bhilai",
    "topic": "media",
    "subtype": "student",
    "claim": "Polaris student guides closest to media; no independent paper verified.",
    "source_url": "https://polaris.iitbhilai.ac.in/",
    "source_title": "Polaris",
    "publisher": "Student body",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Dharwad",
    "topic": "placements",
    "subtype": "portal",
    "claim": "CDC portal with live widget (2025-26 BTech 91.08%, 82LPA highest, 21.15avg). No report PDF; branch median no.",
    "source_url": "https://cdc.iitdh.ac.in/placement",
    "source_title": "CDC placement",
    "publisher": "IIT Dharwad CDC",
    "published_ay": "2025-26",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Dharwad",
    "topic": "rules",
    "subtype": "hub",
    "claim": "Rulebook unverified; statutes/gazette only.",
    "source_url": "https://www.iitdh.ac.in/",
    "source_title": "IIT Dharwad",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "missing"
  },
  {
    "institute": "IIT Dharwad",
    "topic": "fees",
    "subtype": "circular",
    "claim": "MS/MTech fee PDF pattern verified; BTech fee PDF unverified.",
    "source_url": "https://www.iitdh.ac.in/sites/default/files/2026-05/MS%20and%20M.Tech%20By%20Research.pdf",
    "source_title": "Fee example",
    "publisher": "IIT Dharwad",
    "published_ay": "2026-27",
    "format": "pdf",
    "coverage": "partial"
  },
  {
    "institute": "IIT Dharwad",
    "topic": "support",
    "subtype": "counselling",
    "claim": "Counselling centre + Student Welfare Karune/Wellness (+91-81474-03386).",
    "source_url": "https://iitdh.ac.in/counselling-center",
    "source_title": "Counselling centre",
    "publisher": "IIT Dharwad",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Dharwad",
    "topic": "startup",
    "subtype": "incubator",
    "claim": "dhaRti-BioNEST incubator + 2024 incubation call. E-Cell club unverified.",
    "source_url": "https://iitdharti.org/",
    "source_title": "dhaRti incubator",
    "publisher": "IIT Dharwad",
    "published_ay": "",
    "format": "html",
    "coverage": "partial"
  },
  {
    "institute": "IIT Dharwad",
    "topic": "media",
    "subtype": "student",
    "claim": "No independent student newspaper verified.",
    "source_url": "https://www.iitdh.ac.in/",
    "source_title": "IIT Dharwad",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "not_published"
  },
  {
    "institute": "IIT Goa",
    "topic": "placements",
    "subtype": "report",
    "claim": "CDC portal live AY 2025-26 (BTech 116/107 92.24%) + 2021-2025 PDF: branch median YES.",
    "source_url": "https://iitgoa.ac.in/~placement/Placements.html",
    "source_title": "Placements live",
    "publisher": "IIT Goa CDC",
    "published_ay": "2025-26",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Goa",
    "topic": "rules",
    "subtype": "manual",
    "claim": "UG Manual 13-02-2026 + MTech/PhD manuals hub.",
    "source_url": "https://iitgoa.ac.in/academic-rules-regulations",
    "source_title": "Academic rules",
    "publisher": "IIT Goa",
    "published_ay": "2026",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Goa",
    "topic": "fees",
    "subtype": "circular",
    "claim": "BTech Autumn 2026-27 PDF.",
    "source_url": "https://iitgoa.ac.in/wp-content/uploads/B.Tech-Autumn-2026-27.pdf",
    "source_title": "BTech fee 2026-27",
    "publisher": "IIT Goa",
    "published_ay": "2026-27",
    "format": "pdf",
    "coverage": "verified"
  },
  {
    "institute": "IIT Goa",
    "topic": "support",
    "subtype": "dean",
    "claim": "Dean Student Affairs + counsellor + hall office.",
    "source_url": "https://iitgoa.ac.in/student-affairs-dean/",
    "source_title": "Student affairs",
    "publisher": "IIT Goa",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "IIT Goa",
    "topic": "startup",
    "subtype": "incubator",
    "claim": "E-Cell/incubator URLs unverified.",
    "source_url": "https://iitgoa.ac.in/",
    "source_title": "IIT Goa",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "missing"
  },
  {
    "institute": "IIT Goa",
    "topic": "media",
    "subtype": "student",
    "claim": "No independent student newspaper verified.",
    "source_url": "https://iitgoa.ac.in/",
    "source_title": "IIT Goa",
    "publisher": "Institute",
    "published_ay": "",
    "format": "html",
    "coverage": "not_published"
  },
  {
    "institute": "JoSAA",
    "topic": "counselling",
    "subtype": "business-rules",
    "claim": "Business Rules 2026 PDF: supernumerary, Female-Only pool order, preparatory, de-reservation.",
    "source_url": "https://cdnbbsr.s3waas.gov.in/s313111c20aee51aeb480ecbd988cd8cc9/uploads/2026/06/20260601632081678.pdf",
    "source_title": "Business Rules 2026",
    "publisher": "JoSAA",
    "published_ay": "2026",
    "format": "pdf",
    "coverage": "verified"
  },
  {
    "institute": "JoSAA",
    "topic": "counselling",
    "subtype": "or-cr",
    "claim": "OR-CR live query + archive (note spelling Archieve). P suffix = preparatory.",
    "source_url": "https://josaa.admissions.nic.in/applicant/SeatAllotmentResult/CurrentORCR.aspx",
    "source_title": "Current OR-CR",
    "publisher": "JoSAA",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "JoSAA",
    "topic": "counselling",
    "subtype": "seat-matrix",
    "claim": "Seat matrix live query + archive hub.",
    "source_url": "https://josaa.admissions.nic.in/applicant/seatmatrix/seatmatrixinfo.aspx",
    "source_title": "Seat matrix",
    "publisher": "JoSAA",
    "published_ay": "",
    "format": "html",
    "coverage": "verified"
  },
  {
    "institute": "JoSAA",
    "topic": "counselling",
    "subtype": "top20",
    "claim": "Top-20 percentile cutoffs hub, 2026 latest.",
    "source_url": "https://josaa.nic.in/top-20-percentile",
    "source_title": "Top-20 percentile",
    "publisher": "JoSAA",
    "published_ay": "2026",
    "format": "html",
    "coverage": "verified"
  }
];
